<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */
?>
<div class="magepal-extension-search">
    <div class="search">
        <div id="cover">
                <div class="tb">
                    <div class="td">
                        <input type="text" name="search_query" class="search-input"
                               placeholder="Search MagePal Extension Marketplace for..." />
                    </div>
                    <div class="td" id="s-cover">
                        <button type="button">
                            <div id="s-circle"></div>
                            <span></span>
                        </button>
                    </div>
                </div>
        </div>
    </div>
</div>
